services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BenChessterApp
    ports:
      - 8080:8080
    links:
      - mysql1

  mysql1:
    image: mysql
    container_name: mysql1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - mysql1:db
    ports:
      - 8081:80