---
name: "🐛 Bug Report / ✨ Feature Request"
description: "Melde einen Fehler oder schlage eine neue Funktion vor."
title: "[Bug] Kurze Beschreibung"  # Ändere zu [Feature] für Feature-Requests
labels: ["bug", "enhancement"]
assignees: []
---

## 📝 Beschreibung

<!-- Eine klare und prägnante Beschreibung des Problems oder der gewünschten Funktion. -->

## 🔍 Schritte zur Reproduktion (nur für Bugs)

1. Gehe zu '...'
2. Klicke auf '...'
3. Scrolle nach unten zu '...'
4. Fehler tritt auf

**Erwartetes Verhalten:**
<!-- Beschreibe, was stattdessen passieren sollte. -->

**Tatsächliches Verhalten:**
<!-- Beschreibe, was tatsächlich passiert ist. -->

## 📦 Technische Details

- **Betriebssystem:** [z. B. Windows, macOS, Linux]
- **Browser:** [z. B. Chrome, Firefox, Safari]
- **Version:** [z. B. v1.2.3]

## 💡 Zusätzliche Informationen

<!-- Weitere Informationen, Screenshots oder Logs hinzufügen. -->
