services:
  mysql1: #Database
    image: mysql
    container_name: mysql1
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chessmanagement
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  myadmin: #DBMS
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - mysql1:db
    ports:
      - "8081:80"

  chesshub-core: # web-service
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: chesshub-core
    image: ${DOCKER_USERNAME}/chesshub-core:${DOCKER_IMAGE_VERSION}
    links:
      - mysql1
    ports:
      - "8080:8080"
    depends_on:
      mysql1:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql1:3306/chessmanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root